### ISSUE TITLE
How can the simulation cache be cleared?

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#103]
Simulations seem to keep some sort of state when running and interacting with (e.g. press toggle switch) them, then stopping the simulation and restarting it. Is there a way to really restart the simulation without opening another circuit and reopening the circuit that held the state? 
Example: 
1. Open Circuit
2. Start Simulation 
![image](https://user-images.githubusercontent.com/25486087/118886295-08dcfd00-b8f9-11eb-801b-07e653c34b69.png)
3. Toggle S to 1 
4. Toggle S to 0 
5. Stop (not pause!) simulation 
6. Start simulation
![image](https://user-images.githubusercontent.com/25486087/118886462-42156d00-b8f9-11eb-8ec2-6bb550139b22.png)
7. Stop simulation 
8. Open another circuit
9. Re-open original circuit 
10. Start simulation 
![image](https://user-images.githubusercontent.com/25486087/118886609-7db03700-b8f9-11eb-8456-1dd9507c21c4.png)

**Comment by richardabendroth** [comment]
The problem seems to be with the Probe Component: 

![image](https://user-images.githubusercontent.com/25486087/118886896-db448380-b8f9-11eb-8490-57ec23378405.png)

**Comment by flandreas** [comment]
Thank you for pointing this out, great analysis!

Simulation state is distributed among the components and primarily kept in the model layer (primarily ports and wires). There is central code that resets these model states when simulation is started, but the views must be updated accordingly, which can differ depending on the component type. In case of the Probe, it was its view part that wasn't properly updated.
