### ISSUE TITLE
'Wire attach ball' stays in circuit after newly created wire is deleted

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#116]
If wires are created that are only connected on one side and the wire is afterwards deleted right away, the indicator is left on screen until the cursor is moved to an open pin. 

![image](https://user-images.githubusercontent.com/25486087/119167909-a4d54880-ba60-11eb-96fd-001a78b7e1f4.png)

Steps to reproduce: 
1. Create an OR Gate 
2. Mouse-Down on the output pin to drag a wire and drag the wire for a bit but do not connect it to any component
3. Mouse-Up 
4. Move Mouse Pointer to open end of the wire until the yellow full circle appears within the yellow 'wire end' circle
5. While the yellow full circle is present, press Delete on the keyboard 

If the full circle is not visible when pressing Delete, the yellow 'wire end' circle disappears as expected.

**Comment by flandreas** [comment]
Thank you for reporting this.

The same also happens on a pin of a gate, when the gate is selected and deleted with DEL. Only that in this case, the circle disappears after the mouse pointer has been moved away. And the tooltips are also still displayed even if the gate has already been deleted.
