### ISSUE TITLE
Odd wiring behaviour 

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#124]
Sometime the auto-router changes wiring down the path with odd results. Sometimes even leaving the user with wires that can't be moved anymore and are somehow broken. 

![image](https://user-images.githubusercontent.com/25486087/119373577-d9dbd800-bcb8-11eb-8a57-6e94db941a14.png)

![image](https://user-images.githubusercontent.com/25486087/119373751-0bed3a00-bcb9-11eb-9d74-00f39314e07a.png)

**Comment by flandreas** [comment]
Fixed the following scenario that annoyed me for a long time:

<img width="293" alt="before" src="https://user-images.githubusercontent.com/24633141/119607859-5a075800-bdf5-11eb-8cbd-40df746659e1.png">
<img width="293" alt="after" src="https://user-images.githubusercontent.com/24633141/119607874-5ecc0c00-bdf5-11eb-803e-c1c06081cd42.png">

The wire being split is not kept more stable.

<img width="293" alt="new" src="https://user-images.githubusercontent.com/24633141/119608113-ba969500-bdf5-11eb-9f43-f3af8081957f.png">

**Comment by flandreas** [comment]
Also improved logic to avoid non-orthogonal layout solutions. That's all I can do for now. More optimizations would have to be done based on reproducible scenarios.
