### ISSUE TITLE
Joystick component

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#131]
It would be nice to have a rotary encoder as an input component as it is not really possible to emulate this using the existing input components except from two switches and a lot of clicking in the right sequence.

**Comment by flandreas** [comment]
You mean something like "Joystick" in Logisim? What resolution would you expect for the output signals for x and y? Would 9 positions be enough? (8 deflection positions and 1 center/idle position)?

Or something like a representation of an angle, but then without a center/idle position?

**Comment by richardabendroth** [comment]
I mean something like this: 
![image](https://user-images.githubusercontent.com/25486087/120202482-eb782f00-c226-11eb-93ed-a8be3567afa4.png)

While the 'knob' is rotated it gives a constant clock pulse on one output and another clock pulse on the other output that is 90° out of phase compared to the first output. For turning right the phase shift is +90°, for turning left it is -90°. 

I imagine you could utilize something like the clock wheel for user interaction with the switch? But it should only emit pulses when the user is actually 'turning' it; like a momentary button only emits a pulse when the user presses it.  

It could additionally feature a third output that is just a momentary switch ('pressing the knob') but that's just glitter since an additional switch in the circuit would do as well.

**Comment by flandreas** [comment]
Okay, I see. It makes me wonder on what kind of project you are working on... :-)

This is quite a specific component, and I am trying to keep the built-in components as general and widely usable as possible. Wouldn't a "Joystick" component à la Logisim also suit your needs? If Antares would have a "Joystick" component, maybe some users of the Logisim family would decide to start using Antares.

If the joysticks "idle middle position" would break your system, we could perhaps have a property for disallowing this middle position?

**Comment by richardabendroth** [comment]
I am learning about binary counters and BCD and thought this is an easy way of learning about implementing user hardware interaction. This use case does not necessarily require debouncing so it could be done with digital logic only. 
![image](https://user-images.githubusercontent.com/25486087/120325658-2aba8480-c2e8-11eb-9daa-aad01a147534.png)

**Comment by flandreas** [comment]
So would a general joystick component also suffice your needs?

**Comment by richardabendroth** [comment]
I honestly don't know. Would it produce the same sequence of phase-shifted pulses?

**Comment by flandreas** [comment]
I don't now yet. But perhaps we could have a configurable "signal pattern" on the joystick.

**Comment by richardabendroth** [comment]
Sure, why not. I'm currently thinking about just using some gates that produce two phase-shifted signals and package them into a subcomponent like my HEX switch in #136.

**Comment by richardabendroth** [comment]
I found an actual component that would come very close to the UI of the existing DIP switch: 
![image](https://user-images.githubusercontent.com/25486087/121008688-8d51cb80-c793-11eb-8d97-b9c31ed4b97d.png)

**Comment by richardabendroth** [comment]
I've built a component out of basic Antares Components and it works okay-ish. As mentioned in #136 I'm having problems with the right delays. But it should be able to illustrate what I mean. 
![image](https://user-images.githubusercontent.com/25486087/121345010-a3db5c80-c924-11eb-9a5b-5bf3a85d1ac2.png)
Here is the circuit: 
![image](https://user-images.githubusercontent.com/25486087/121344240-d2a50300-c923-11eb-9b60-2acc9b4496de.png)

**Comment by flandreas** [comment]
Impressive!

**Comment by flandreas** [comment]
First joystick implementation.

https://user-images.githubusercontent.com/24633141/121810184-15d2df00-cc60-11eb-978b-36dc952f245c.mov

Produces signal x: Indicates knob's x-coordinate, to be interpreted as an unsigned integer whose value will never be 0. Thus, a value of 1 represents the far left, and the maximum value for the bit width indicates the far right. When the knob is at rest (in the center), the value has the bit pattern 10...00.

Same applies for signal y.

The joystick has a property for choosing "rectangular" or "circular" deflection.

**Comment by flandreas** [comment]
And here a run with the oscilloscope:

https://user-images.githubusercontent.com/24633141/121815485-0e6b0000-cc77-11eb-9e7c-ea52374e932a.mov

**Comment by richardabendroth** [comment]
Nice! So when I just use bit 0 of each X and Y, I would exactly get the behavior of a rotary encoder! Now I understand! Cool! By the way, the oscilloscope is such a cool feature! Can't wait for it to arrive in userland 😊

**Comment by flandreas** [comment]
Yes!
