### ISSUE TITLE
Allow reconnecting existing net to an input/output

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#134]
This might be related to #5. It's quite laborious to reconnect an existing net to an input. This happens quite often if you have an input component or a component output feeding a net that is connected to a number of inputs of other components. If the user then deletes the wire between the output and the rest of the net, the whole net needs to be deleted and recreated. 

![image](https://user-images.githubusercontent.com/25486087/120199993-2036b700-c224-11eb-82c0-99d1ddd80a7b.png)

**Comment by flandreas** [comment]
Yes, and it's also related to #75.
