### ISSUE TITLE
Cant Edit ROM values anymore

### ISSUE THREAD

**Issue by Kitick** [flandreas/antares#146]
I'm no longer able to edit any ROM data, and the import button is also gone!

**Comment by flandreas** [comment]
Oh, sorry for that! This bug arose when disallowing RAM contents to be edited in edit mode, because RAM resets its content anyway when the simulation is started.
Will soon be fixed with the upcoming 0.6.1.

**Comment by Kitick** [comment]
Alrighty thanks!
