### ISSUE TITLE
Strange behavior with pull-up resistor on simulation start

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#150]
I have placed an improvised 'real' button within a circuit with a pull-up resistor and when starting the simulation it seems to transmit low. 
![image](https://user-images.githubusercontent.com/25486087/120634080-266aa480-c46b-11eb-9b98-fe2653efe5b0.png)

After interacting with the circuit the first time it works flawlessly. 

![image](https://user-images.githubusercontent.com/25486087/120634370-747fa800-c46b-11eb-9a76-78dabfe917e7.png)

What am I doing wrong? 

Here is the circuit of my improvised button: 
![image](https://user-images.githubusercontent.com/25486087/120634482-96792a80-c46b-11eb-97a6-c7d664303897.png)
(I know that I'm using a limitation of the simulator to detect the high impedance)

**Comment by flandreas** [comment]
Seems to be a bug in the circuit bootstrap algorithms regarding the collaboration of pull resistors and signal sources within sub circuits. I will look into it..

**Comment by flandreas** [comment]
It doesn't even require sub circuits. The minimal circuit producing this bug looks like this:
<img width="191" alt="bug-150" src="https://user-images.githubusercontent.com/24633141/120751029-9cbce480-c507-11eb-89fc-fcb54c4b25bc.png">
So, a "weak" signal doesn't get forwarded correctly on a net on start-up

**Comment by flandreas** [comment]
Important issue, requires quite some changes in the simulation start-up procedures...

**Comment by richardabendroth** [comment]
What I have also noticed is that Z doesn't propagate on startup: 
![image](https://user-images.githubusercontent.com/25486087/120890482-41701c80-c603-11eb-8808-8ddccfcf374e.png)
After opening and closing both switches, Z is successfully propagated into the subsequent net: 
![image](https://user-images.githubusercontent.com/25486087/120890519-75e3d880-c603-11eb-817e-4f139fadc00e.png)

**Comment by flandreas** [comment]
Thank you.

**Comment by flandreas** [comment]
Fixed all known scenarios. But, honestly, as this is a pretty complex topic, I'm not entirely sure if this covers all possible scenarios. We'll see..
