### ISSUE TITLE
Renaming Circuits

### ISSUE THREAD

**Issue by Kitick** [flandreas/antares#156]
Just a quick question, is there a way to rename circuits without duplicating and deleting?

**Comment by flandreas** [comment]
Yes, you can change a circuit's name by changing it in the circuits properties. Open the circuit, click on its background to make sure the circuits properties are displayed, change property "Name", and finally save the circuit.

**Comment by richardabendroth** [comment]
There is also a feature request (#47) to make this procedure more intuitive.
