### ISSUE TITLE
Feature Request: Order of Folders in Explorer

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#161]
The order of Folders within the 'Project' section in the Explorer seems to be defined by the order of creation. There should be a way to reorder Folders like Circuits can be reordered.  Furthermore, when ordering Circuits, Antares asks if the user wants to move the component into the Project, even though it is already in that Project.

**Comment by flandreas** [comment]
If I remember correctly, I didn't implement this in the first place because I wanted to avoid complications when dragging an entire folder from the project to a library or the other way round. But yes, this feature would surely be useful.
