### ISSUE TITLE
Unconnected Probe shows that it is connected to 0

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#167]
An unconnected probe claims that is receiving 0. Shouldn't this be Z instead? 
![image](https://user-images.githubusercontent.com/25486087/121704796-5e5d9180-cad4-11eb-9bdf-5e07f8d377a6.png)

**Comment by Kitick** [comment]
I think it should be 'Z'.

**Comment by flandreas** [comment]
Yes, you're probably right.
