### ISSUE TITLE
Double Throw Switch

### ISSUE THREAD

**Issue by Kitick** [flandreas/antares#169]
I actually don't know what they're called, but its a switch, that has three pins, A, B and Y (or Q?). And whatever the switch is set to, it passes that signal to Y. So if the switch is in A, then whatever A is, Y is, if its on B, then if its B, then B. The layout is actually A Y B, but same difference.

I have a picture of it if it helps:
![20210611_085603](https://user-images.githubusercontent.com/34259991/121715142-677a3e80-ca93-11eb-8f6b-8a05b3e309fe.jpg)

**Comment by richardabendroth** [comment]
It's called double throw switch. I can build one for you based on the one I've posted in #144.

**Comment by Kitick** [comment]
Ah, I knew that it had 'Throw' in it I just was unsure exactly. Thanks for clarifying!

I think you can just use a 2:1 Multiplexor, unless the output should carry undefined when A or B is undefined.

**Comment by richardabendroth** [comment]
Well yes and no. If you indeed don't care about the Z signal, the normal switch also works using an AND gate. But especially for the Double Throw Switch, which does not only direct the signal into the selected direction, it does also allow you to combine signals from two sources and exclusively forward the selected one to the receiving net. So the 'Y' goes both ways: A or B to Y and Y to A or B.

**Comment by richardabendroth** [comment]
This is what I came up with: 
![image](https://user-images.githubusercontent.com/25486087/121736778-4ef03f80-caf8-11eb-9f3a-4cd0879f6e55.png)
![image](https://user-images.githubusercontent.com/25486087/121737908-ca9ebc00-caf9-11eb-8ac0-b8caba72ea42.png)
![image](https://user-images.githubusercontent.com/25486087/121737945-d7231480-caf9-11eb-858a-b6668c0321b3.png)

**Comment by richardabendroth** [comment]
But indeed, having this as a standard component with the right button symbol and without my direction 'DISPLAY' hack would be wonderful!

**Comment by richardabendroth** [comment]
UPDATE: Above circuit seems to glitch in Y to A or B condition. I'm investigating...

**Comment by Kitick** [comment]
What's stopping you from just doing this?

![image](https://user-images.githubusercontent.com/34259991/121761772-9241b280-cae6-11eb-90a3-52bc6f59746d.png)

**Comment by Kitick** [comment]
UPDATE:

Oh I see, your having it be two way, ahh, alright I get it, that seams like it would need more logic, lemme give it a try and see what I come up with

**Comment by flandreas** [comment]
@richardabendroth I've reproduced your circuit for analysis, and it seems to just work as expected, at least on my development version 0.6.2-beta. Could you please explain what you meant by "seems to glitch in Y to A or B"?

**Comment by flandreas** [comment]
Implemented with release 0.20.0
