### ISSUE TITLE
Tri-State Buffer wire glitching when changing Control Input Direction while Signal connected

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#170]
The Signal wire of the Tri-State Buffer glitches when changing Control Input Direction while a signal net is connected. 
![image](https://user-images.githubusercontent.com/25486087/121732874-0a15da00-caf3-11eb-9832-415e8b7c9889.png)

Steps to reproduce: 
1. Place a Tri-State Buffer
2. Connect any wire 
3. Change 'Control Input Signal Direction' property to 'left' 

The problem disappears after saving and reopening or when deleting and reconnecting signal wire after Control Input Direction property change.

**Comment by flandreas** [comment]
Thank you for reporting this.

**Comment by flandreas** [comment]
The current version rebuilt the component's view from scratch when the "signal direction" property has been changed, thereby loosing state information. The fix keeps and adjusts the existing view. Unit test added.
