### ISSUE TITLE
Why do Outputs have a 'Switch' (ex. 'Toggle') property?

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#171]
I seem not to be able to discover why Outputs have a 'Switch' (ex. 'Toggle') property. Since Outputs are not clickable, what is it for? For inputs and inputs/outputs I completely understand the purpose but for Outputs, it doesn't seem to do anything.

**Comment by flandreas** [comment]
Oh, that's probably a bug, possibly caused by shared bean properties logic for inputs and outputs. I will look into it.
