### ISSUE TITLE
LED is outputting 1?

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#175]
In the following circuit, the net on B and the net on Y are both 1 but B is only connected to an LED and both tri-state buffers that isolate its net within the circuit are non-conducting. What is happening? Shouldn't turn B into Z state?
![image](https://user-images.githubusercontent.com/25486087/121752909-7ef80c80-cb11-11eb-8c66-be83bdefb5e8.png)
![image](https://user-images.githubusercontent.com/25486087/121752950-8f0fec00-cb11-11eb-868d-58aa063484bf.png)

**Comment by flandreas** [comment]
Yes, there is something going wrong. Could you please attach your project for analysis?

**Comment by richardabendroth** [comment]
Oh god, all my learning circuits are in a monster project. I'll try to figure out a good way to get it out of there.

**Comment by flandreas** [comment]
Never mind, I think I can reproduce your scenario on my own.

**Comment by flandreas** [comment]
See also #169

**Comment by flandreas** [comment]
@richardabendroth I've tried to reproduce your circuit, but wasn't able to figure out how the circuit looks like in the regions missing in your screenshot. May I ask to to post a screenshot containing the entire circuit?

**Comment by flandreas** [comment]
Probably related to #227. If not, please reopen.
