### ISSUE TITLE
Purely scripted components

### ISSUE THREAD

**Issue by flandreas** [flandreas/antares#188]
As already discussed in other issues, there is a need for user-made components that don't contain an inner circuit, but whose execution logic is entirely defined by an execution script. The inner circuit would only contain input and outputs in order to define the "interface" of the component.

This could be useful in the following scenarios:
- Users are missing a built-in component, but cannot work around this by designing their own circuit because needed constructs/parts are missing (example: Real Switch)
- Support Top-Down approach: Teachers provide systems that are fully functional, so that the user can play around with it, but some sub circuits are defined as scripts, and the goal of the student is to replace the scripted components by  self-developed sub circuit that use real circuit logic.

Such components would be marked by the designer as "Purely scripted", so that their script is always executed, even if the simulator runs in "deep simulation mode".

**Comment by Kitick** [comment]
I think this is a good idea, where there just are components that are scripted by nature, for when you just want the logic, and or like you said, to have a goal, and to try to reproduce with real logic.

This does open another thing that I wanted to discuss, but I'll open a new issue for it.
