### ISSUE TITLE
A sound player / Speaker component

### ISSUE THREAD

**Issue by Kitick** [flandreas/antares#210]
Alright, this came from #209, but this can be implemented without it

What if there was a component that played little 8 bit beep sounds, and the pitch was controlled by a binary input, and whatnot? And there could be a type selector to change it to other types of sounds, like piano or drums
This is purely a fun component, and would defiantly be after the more important stuff was put in first. But know knows, I think it could be fun, you could add beep codes to computers, or make a full on music player lol

**Comment by flandreas** [comment]
Yes, that's a good suggesting for a fun feature.

**Comment by flandreas** [comment]
Upcoming with release 0.15.0.
<img width="150" alt="buzzer" src="https://user-images.githubusercontent.com/24633141/143217443-01ebc549-217a-4531-b122-171de781ae63.png">
