### ISSUE TITLE
Splitting wires can ruin layout of existing wire

### ISSUE THREAD

**Issue by flandreas** [flandreas/antares#213]
When repeatedly splitting wires, the layout algorithm can ruin the layout of the existing wire being split.

<img width="213" alt="layout" src="https://user-images.githubusercontent.com/24633141/127533355-b66ef650-bb46-4110-955f-316bc2816d23.png">

**Comment by Kitick** [comment]
@flandreas this is similar to my issue #186, where it would just mess up all of the wire organization when splitting, or sometimes simply moving a component.
