### ISSUE TITLE
Lower entry barrier for first-time users

### ISSUE THREAD

**Issue by flandreas** [flandreas/antares#214]
Put yourself in the position of someone using Antares for the first time and imagine the barriers she is facing. Take the resulting necessary actions that lower the entry barrier and reduce the risk to loose potential users on their first try-out.

Barriers identified so far (and possible actions)
- DONE: Issue #86: Security check warnings when installing on Windows -> Sign application (applies also to macOS)
- DONE: New user preference "Show tips for beginners"
- DONE: Create wire junctions -> Show a tooltip on wires saying "Press ALT to create a junction".
- DONE: Tooltips in workbench tree

**Comment by Kitick** [comment]
I totally agree! Antares is such a great program even now, it would suck if someone got scared away just because of the windows smart screen error!
