### ISSUE TITLE
Component: Signal Replicator

### ISSUE THREAD

**Issue by Kitick** [flandreas/antares#217]
This goes inline with the whole bit width to the gates, where there should be a component specifically designed to replicate a signal across different bit widths. So for example, you could have a 8 Bit AND gate or XOR gate, and use a switch with a replicator to act as the enable. The replicator should simply just produce a constant 0000 0000 or 1111 1111 based on the input.

Another idea is, just add the bit width to switches, and have the switch just output a constant 0x or 1x based on the width. This would replace the need for a separate component. Unless this separate replicator could have other uses?

Edit: So as I did more testing, having a separate component would be a good idea, because for my 64 Bit adder for example, I want one switch to turn it to a subtractor. And that would mean I need a 64 bit XOR gate, and a 1 Bit XOR gate, one for the input, and one for the carry. (Yes I could use a 64 Bit XOR and just use one port, but that seams like poor way to do it). And so Id need two switches. one 62, and one normal. Instead of having one, and having it tied to the carry, and to the replicator. and the replicator to the XOR.
But I still think having it on the switch as well could be useful. I'll leave that up to you.

**Comment by flandreas** [comment]
Good suggestion! I think we'll go with the signal replicator component (or "Bit Extender", as other tools call it). We should probably make it slightly more versatile right from the start, such that it can map n:m signals.

**Comment by flandreas** [comment]
Implemented.

<img width="492" alt="BitExtender" src="https://user-images.githubusercontent.com/24633141/128342297-0e4164bb-a954-48e8-b9e2-cced5c6f73c8.png">

**Comment by Kitick** [comment]
Awesome! Looks great!
