### ISSUE TITLE
History of saved Circuit versions

### ISSUE THREAD

**Issue by Kitick** [flandreas/antares#219]
I totally understand why it's doing this, however I would like to suggest to have a way for the undue states to be saved even after the circuit gets saved, because they were instances where I did a small change just to see what it did, and then I clicked save by habit before starting the simulation, and then when I went back to undo it wouldn't, because I saved.

Maybe just have it always save I don't know the last 10 or states of the circuit in a log file? And when the entire program is closed those extra log files are deleted

**Comment by flandreas** [comment]
Yes, I think this idea calls for something like a "save history" that is maintained in log files, and that allows you to revert to older versions of your project. This could be a useful feature, and it shouldn't be that hard to implement.

**Comment by Kitick** [comment]
I agree, that could be very useful actually!

**Comment by flandreas** [comment]
Implemented a "Save History" for each circuit including the possibility to restore an old version

**Comment by flandreas** [comment]
Released with 0.23.0
