### ISSUE TITLE
Signal from tri state buffer stays lo/hi

### ISSUE THREAD

**Issue by ZoBoRf** [flandreas/antares#228]
After starting the simulation in 0.12.1 the situation is as follows:

![grafik](https://user-images.githubusercontent.com/169823/135604975-65020cac-eb58-4918-a04d-26e8feaf967e.png)

now set EN=1

![grafik](https://user-images.githubusercontent.com/169823/135605312-3ba4ecb0-fb03-42c5-924e-030c0972b637.png)

now set EN=0

![grafik](https://user-images.githubusercontent.com/169823/135605069-fd742edf-ff3e-4308-9e9c-cfe6a9e0bb4e.png)

The bidirectional outputs are not reset to Z.
Is this correct?

**Comment by ZoBoRf** [comment]
Remark: 

The simulator Hades (https://tams.informatik.uni-hamburg.de/applets/hades/webdemos/90-tionline/06-ralu/tri.html) resets the outputs to Z, after the tristate buffers are deactivated.

![grafik](https://user-images.githubusercontent.com/169823/135613300-45881326-2c37-4656-ba9a-e873a159a86c.png)

**Comment by flandreas** [comment]
No, that's not correct, thank you for pointing that out. There is indeed a unit test missing for this scenario.
