### ISSUE TITLE
Circuit Analysis: Create Expressions from Circuit

### ISSUE THREAD

**Issue by Kitick** [flandreas/antares#234]
Alright, so this is obviously low priority in terms of everything else, but I think it could be an interesting addition.

So as you know you can rewrite circuits as a algebraic expression, which then can be used to simplify, and re write a circuit with say, only one type of gate, or just simplifying in general.

Well, why not have Antares generate the algebraic expression for the current circuit? If the user clicks the button say, generate expression. Not simplify, that's its own thing entirely, just generate the current circuit how it is. So if I were to build say a full adder with two half adders, and named the inputs A, B, and CI; And the outputs as S and CO, then the expression would return:

S = A*B*(CI)
CO = AB + (A*B)(CI)

(* = XOR)

Just as an example, it would just start at the outputs, and keep going backward until it hit only inputs. It would see that S is connected to the output of a XOR, so the first level is S = ? * ?, then it goes down input one, sees that's an XOR as well, so its now S = (? * ?) * ?, then down input one of that second XOR is A, so (A * ?) * ? input two for that is then B: (A * B) * ? Then back to the first XORs second input, is CI, so the final expression is (A * B) * CI. And the same procedure can be done for the CO calculation, its just more complicated. Not sure how to avoid confusion if CI were to be interpreted as C AND I, but that can be figured out.

Latches are just simply if it sees that an input was wired back to an output, then that uses a different symbol to show that its a latch output, and that stops there instead of at an input.

Let me know what you think, if this is even something useful at all, or if it would be too much of a pain to implement. Personally, I would use this to help simplify circuits, rewrite with one gate type, or use it for a script to evaluate rather then simulating the real gates. That last one could potentially be the start of a auto script generator for super fast execution, just evaluating expressions.

Anyway thanks for the read!

**Comment by flandreas** [comment]
Thank you for your suggestion.

Circuit analysis and synthesis is a topic Antares doesn't touch on so far, but it's surely something worth looking at. Similar tools support this too, and Antares probably won't be "Feature Complete" until it supports at least the basics in this area.

Your suggested algorithm sounds reasonable, but it will quickly lead to long and complicated terms for non-trivial circuits. I suppose you can't do without some sort of minimizing algorithms, anything that is equivalent to Karnaugh maps (e.g. Quine-McCluskey).

I'll put the "Feature" label to your suggestion, but I can't promise too much about the priority of this feature at this point.

**Comment by flandreas** [comment]
@Kitick Now that release 0.21.0 contains features for defining truth tables and generating minimized expressions, and development for parsing expressions entered by users is underway, the foundation is ready for this feature here.

My first approach is to build a truth table for every input and output component in the circuit, run a simulation in the background with all possible input combinations, and capture the results arriving at the output in the truth table output column. Antares can the use the already present feature for deriving minimized expressions from a truth table.

**Comment by flandreas** [comment]
Released with 0.22.0
