### ISSUE TITLE
"Constant" can not be rotated using ctrl+r or right click

### ISSUE THREAD

**Issue by aquamiau** [flandreas/antares#273]
"Constant" can not be rotated using ctrl+r or right click, only through the "Orientation" property.

**Comment by flandreas** [comment]
Thank you for reporting this. Yes, I got annoyed by this flaw myself. I think there are some other components also missing this capability, mainly those that display signals as hex or binary numbers, because those behave differently regarding rotation. I will look into this.

**Comment by flandreas** [comment]
Implemented for Constant, Probe and DIP Switch
