### ISSUE TITLE
Show Simulationtime in Statusbar

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#281]
Tickin the Option under "Simulation"->"Show Simulationtime in Statusbar" just enables the Option for this Time. Closing and reopening the Program resets this Setting.

**Comment by flandreas** [comment]
This is a feature. Updating the simulation time in the statusbar is somehow costly, and I like to avoid it if the user haven't requested it explicitly.

**Comment by flandreas** [comment]
@leonuetzel Would it be okay for you if the option would not be reset when restarting the application, but the statusbar would only be updated if the simulation is NOT running in simulation mode "Execute" (i.e. as fast as possible)?

**Comment by leonuetzel** [comment]
Yeah sure that would be ok.
