### ISSUE TITLE
Zooming too near in Symbol editing Mode switches to Circuit Editing Mode

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#284]

**Comment by flandreas** [comment]
This is a feature. The same happens in the circuit editing mode: zooming out very far switches to the symbol editing mode. It's a way to switch between the two mode using zoom.

But I can imagine how this can confuse users. What do you think? Is this useful or mainly confusing?

**Comment by leonuetzel** [comment]
I wanted to place a circle very exactly so i switched off the alignment and zoomed very near.
Then i found the Option "Align to" and since then i dont need to zoom that far in, so i think its a nice feature now.

**Comment by flandreas** [comment]
Okay, thanks!
