### ISSUE TITLE
Connecting a wire to another wire isnt possible

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#295]
Im trying to connect two wires together that have been released already.
The Program doesnt connect them together (see Pictures
![before](https://user-images.githubusercontent.com/39810063/152050428-a92d1cbe-ed71-4817-88dc-9a9ea2cdbdb9.PNG)
![after](https://user-images.githubusercontent.com/39810063/152050436-1961f0c8-f9a6-4cb3-9f44-c4c03f878da0.PNG)
)

**Comment by flandreas** [comment]
Yes, this has not yet been implemented. It's probably a special case of your issue #296.

**Comment by flandreas** [comment]
Workaround: After #5 has been released, you can drag the end point onto the other wire and create a new junction, and then trim off the dangling wire manually. I'm not sure whether it's worth it to support this special case as well.
