### ISSUE TITLE
Connecting wire to already exisiting wire doesnt work

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#296]
![before](https://user-images.githubusercontent.com/39810063/152050670-e247d57a-827c-4883-9287-66491eb524fb.PNG)
![after](https://user-images.githubusercontent.com/39810063/152050672-f7dbdf83-512f-4ac2-b5d2-48e41534ab01.PNG)

**Comment by flandreas** [comment]
Yes, not yet implemented. Same as issue #5 .
