### ISSUE TITLE
Flat Simulation Script Error

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#298]
![error](https://user-images.githubusercontent.com/39810063/152162367-d8d52db0-7597-4f93-948e-334fbbf29dfe.PNG)
![circuit](https://user-images.githubusercontent.com/39810063/152162369-1262d189-2315-44a4-a624-afbe25a7ffbe.PNG)
Tried to use Flat Simulation for a simple Multiplexer i created, but Antares throws Errors.
What am i doing wrong?

**Comment by flandreas** [comment]
Your are trying to access individual bits of a bus input using an array accessor. That doesn't work.

You have to use the bit access operator @. Try the following:
```
OUT = IN@SW
```

**Comment by flandreas** [comment]
BTW: For questions like this (which are always welcome), you can also use the project's discussion board.

**Comment by leonuetzel** [comment]
Ah ok, thank you.
Next time i will use the discussion board.

**Comment by flandreas** [comment]
Answered
