### ISSUE TITLE
Opening ROM in Circuit results in Error

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#303]
Trying to open
CPU->ProgramMemory->ROM
![error](https://user-images.githubusercontent.com/39810063/152859877-9fe80d48-1b10-4ad7-b7bb-06a3c7c4ada1.PNG)

to edit the Memory results in an unexpected Error.

**Comment by flandreas** [comment]
@leonuetzel Yeah, that's a bug. It occurs when you open a memory component in a circuit that is not the top-level circuit, i.e. after diving into a sub circuit. Never tried that before. Thank you for reporting this.

BTW: Editing ROM content in a sub circuit wouldn't be possible anyway. For editing, you would have to open "ProgramMemory" as top-level circuit.

**Comment by leonuetzel** [comment]
Ah ok, good to know. Guess i will put the ROM Circuit directly into the CPU for easier testing.

**Comment by flandreas** [comment]
Fixed with release 0.20.0
