### ISSUE TITLE
Error while dragging components

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#375]
Heres a Logfile of a Crash that happened right now.
If u need the Project, please tell me
[Antares.log](https://github.com/flandreas/antares/files/8660990/Antares.log)
.

**Comment by flandreas** [comment]
@leonuetzel Thank you for reporting this. Seems to be a regression problem in the "move component" logic that has been introduced with the new features "Orthogonal move" and "Move without snap".
