### ISSUE TITLE
Error while diving into subcircuit with running signal flow animation

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#377]
Dont know if its a duplicate so i just upload the Logfile here..
[Antares.log](https://github.com/flandreas/antares/files/8663967/Antares.log)
.

**Comment by flandreas** [comment]
@leonuetzel Thank you for reporting. This is something new.

Seems to be a problem with diving into a subcircuit while signal flow animations are running. In your case, it occurred while executing a use case; I don't know yet whether this is relevant.
