### ISSUE TITLE
Extract single Bit from Bus

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#402]
It would be nice if there existed a Component to extract a single Bit from a Bus instead of having to create a (for large Bus Widhts very big) Expander.

**Comment by flandreas** [comment]
@leonuetzel Like the inverse of „Bitwith extender“, with the possibility to choose the source bit position?

**Comment by leonuetzel** [comment]
And additionally the Possibility to choose the Output Bit Width

**Comment by flandreas** [comment]
Yes, sounds good.
