### ISSUE TITLE
Error on Simulate Subcircuit View

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#403]
On viewing Subcircuit "Register 1 Bit" of Circuit "Clock" in "Parts->Clock" during Simulation, an unexpected Error occurs.
[Antares.log](https://github.com/flandreas/antares/files/8943390/Antares.log)

![Unbenannt](https://user-images.githubusercontent.com/39810063/174671370-c57368a0-23e5-4816-af83-71033f8f8e3c.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/39810063/174671592-60b33c4c-bdbc-49c2-ac74-8b242edde0a1.PNG)
![Unbenannt3](https://user-images.githubusercontent.com/39810063/174671593-8fbece30-0c52-46f2-813b-18ce00587cc6.PNG)

[FPU.zip](https://github.com/flandreas/antares/files/8943393/FPU.zip)

Btw: V27.0, dont know if relevant anymore.

**Comment by flandreas** [comment]
@leonuetzel Thank you for reporting this. This was a bug that has been fixed in 0.27.1. I've tried in your project with 0.29.0, and the error doesn't occur.
