### ISSUE TITLE
Propagation Delay of NAND is incorrectly simulated

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#404]
![grafik](https://user-images.githubusercontent.com/39810063/174684524-ac986bb9-376f-438c-9aa0-216d73aef0e4.png)
The NAND in this Subcircuit shows a Delay of 5ns on the second incoming Signal Wave.
Reproduce with Starting Simulation, set "Pulse" to 3, then press "EN" and wait for the 2nd Wave to reach the Subcircuit. The NAND propagates the Signal after ca. 5ns, instead of the set Value of 20ns. Its clearly observable by watching the 2nd Wave propagating through the NOT-Delays, where the 2nd Wave is shorter than the 1st (which took about 10 NOT-Delays instead of ca. 2-3 for the 2nd Wave)
Folder "Parts->Clock" -> Circuit "Clock"
[FPU.zip](https://github.com/flandreas/antares/files/8943994/FPU.zip)
Again V27.0

**Comment by flandreas** [comment]
@leonuetzel Thank you for reporting this. I'm analyzing...

**Comment by leonuetzel** [comment]
Ok sry then for bothering you, should have looked more carefully before opening an Issue.

**Comment by flandreas** [comment]
@leonuetzel No problem, I'm always glad when I can help.
