### ISSUE TITLE
Right click on side bar items opens menu of the currently selected item instead of the item clicked

### ISSUE THREAD

**Issue by aquamiau** [flandreas/antares#415]
Right click on side bar items opens menu of the currently selected item instead of the item clicked.
For visual clarity, selecting the right clicked item would also be useful.

**Comment by flandreas** [comment]
@aquamiau Thank you for this input. Good point. I'll try to implement as you've suggested.

**Comment by flandreas** [comment]
Implemented. Applied as well to the scenario and use case trees.
