### ISSUE TITLE
Multiplexer n Bit works differently than other multiplexers

### ISSUE THREAD

**Issue by aquamiau** [flandreas/antares#419]
n Bit Multiplexer output Z when Z or no inputs are connected, while regular multiplexers output 0:

![grafik](https://user-images.githubusercontent.com/573744/178016367-03d83aad-c464-4994-a145-3bc3bd516157.png)

**Comment by flandreas** [comment]
@aquamiau Thanks for reporting this, that's surely a bug. The multiplexers (and others sub circuits with generic bit with and calculation script) should respect the configured "Undefined Gate Input Behavior" like concrete logic gates also do.

**Comment by flandreas** [comment]
Added new global DSL function `gated()` to apply "Undefined Gate Input Behavior" when reading input signals in execution scripts.

Used in "Multiplexer n Bit" sub circuit in standard library.
