### ISSUE TITLE
Allow changing "Position Bit 0" for Splitter, Combiner, Bidirectional Splitter

### ISSUE THREAD

**Issue by aquamiau** [flandreas/antares#423]
After a splitter or combiner are placed and a wire has been connected, it is no longer possible to change "Position Bit 0" to flip the orientation.

**Comment by flandreas** [comment]
@aquamiau Yes, this is intentionally not possible, because it was much easier to implement this way. It would also completely mess up the layout of connected wires if that would be allowed.

However, it would not be impossible to implement it. Do you miss it much?

**Comment by aquamiau** [comment]
Well, there are workarounds, like deleting it, creating a new one and reconnecting all the wires (which can be annoying for 32 or 64 bit) or making a component out of it that can be mirrored - so it's not something that has high priority. I do think though that it should be added at some point for those who try to 
find good layouts that are easy to follow.
I don't know how exactly it would affect wires, if they all need manual adjusting afterwards anyway, but it might work in cases like this without messing them up:

![image](https://user-images.githubusercontent.com/573744/178542686-1072b714-61b0-4e6c-8c96-716e7e5c0999.png)

**Comment by flandreas** [comment]
@aquamiau Okay, you got me. Accepted as "feature" with low priority.

**Comment by flandreas** [comment]
BTW, in the meantime, as a workaround, you could also manually de-connect the wires from the splitter, leave the open-ended near the old pin position, alter the splitter's property, and connect the open-ended wires again. This eliminates the need for deleting the entire wire.

**Comment by flandreas** [comment]
@aquamiau Sorry, forget my last comment, I wasn't reading your comment precisely enough. Your workaround with deleting the splitter and re-creating it is of course much better.

**Comment by flandreas** [comment]
@aquamiau Done. It was much easier than I thought.
