### ISSUE TITLE
Improve unexpected error window

### ISSUE THREAD

**Issue by p-** [flandreas/antares#43]
Hi @flandreas 

Small suggestion for the unexpected error window:
![antares-error](https://user-images.githubusercontent.com/176818/105575064-aae04480-5d60-11eb-9de6-57d7026778a6.png)

It would be helpful if you added something like a "copy error to clipboard" button and added a clickable link to the right bug tracker (I assumed it's this one.)

Hint for other users wanting to report an error: Go to "File/Export Log file". Open the generated zip file and copy the relevant exception (Most likely starting on a line containing "ERROR".

**Comment by flandreas** [comment]
Thanks for your suggestion.I will probably also add a new sub page to the project home page that contains more description regarding bugfix reporting, e.g. how and when to change the LOG level before reproducing an error.
