### ISSUE TITLE
Suggestion: add one or multiple small videos to the front page

### ISSUE THREAD

**Issue by p-** [flandreas/antares#44]
As the title says: create some short videos without sound for the Antares front page (and maybe also for subsequent pages.

For example like this (it's a little big though and unfortunately a GIF):

![keyboard_lcd](https://user-images.githubusercontent.com/176818/105575419-728e3580-5d63-11eb-974e-8302c0518bfe.gif)

I think Antares capabilities are much more apparent in videos.

Alternatively put some screenshots on the front page 😉

**Comment by flandreas** [comment]
That's a good idea! I'll do that..
