### ISSUE TITLE
Wrong decoder behaviour in flat simulation

### ISSUE THREAD

**Issue by LuminousXLB** [flandreas/antares#564]
As in the figure below, the expected output is 7 but 1 is given.

![image](https://github.com/flandreas/antares/assets/23524048/2f3fd82b-f7c9-417f-ac0a-e57b75933f1b)

Here's the script:
```
var val = I0 + 2 * I1 + 4 * I2
O0 = EN and val == 0
O1 = EN and val == 1
O2 = EN and val == 2
O3 = EN and val == 3
O4 = EN and val == 4
O5 = EN and val == 5
O6 = EN and val == 6
O7 = EN and val == 7
```
I guess the first line shall be changed to `var val = 1 * I0 + 2 * I1 + 4 * I2` to cast it to number instead of bool.

**Comment by flandreas** [comment]
BTW, the same bug is also in the scripts for 2-4 DEC and 4-16 DEC.
