### ISSUE TITLE
Numeric keyboard not working on Circuit Input

### ISSUE THREAD

**Issue by LuminousXLB** [flandreas/antares#579]
This is tested on Windows 11 with v1.4.0. 

I cannot use my numeric keyboard to input into the Circuit Input.

![image](https://github.com/flandreas/antares/assets/23524048/e3285b3d-e393-4794-85e9-c4cc09d08b7d)

![image](https://github.com/flandreas/antares/assets/23524048/c39ed65e-5881-45f1-b6f3-621cffc1f437)

**Comment by flandreas** [comment]
@LuminousXLB Good suggestion, thank you!
