### ISSUE TITLE
Open-ended wire can sometimes not be reconnected

### ISSUE THREAD

**Issue by flandreas** [flandreas/antares#582]
When deleting a connected component, the resulting open-ended wires can sometimes not be reconnected to another component.

Example:

<img width="473" alt="Screenshot 2023-06-08 at 08 54 51" src="https://github.com/flandreas/antares/assets/24633141/74fda890-98cd-439c-8b66-232b9e30592e">

1. Delete inverter
2. Reconnect the now open-ended wire at output of OR gate to pin of O2

=> The pin at O2 won't accept the wire

**Comment by medennis34** [comment]
![antaresSS3](https://github.com/flandreas/antares/assets/132152600/5de01741-2c5d-4d72-be47-91c0dde8ab46)
I think I have a similar problem.  I deleted a wire between the clock (set) and the buffer enable and there appears to now be an invisible short.

**Comment by flandreas** [comment]
@medennis34 Sorry, I just saw your comment now.

Do you remember what the tooltip said when hovering over one of the wires in error state (the red ones)?.

**Comment by flandreas** [comment]
Cannot be reproduced any more.
