### ISSUE TITLE
Buffer and NOT gate miss input negation

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#586]
The Buffer and NOT gate components miss the input negation properties.

**Comment by flandreas** [comment]
@richardabendroth This is by intention, because we thought inverting inputs on buffers and NOT gate would just be equivalent with the respective counterpart. Do you see any practical usage of inverting inputs of buffers and NOT gates?

**Comment by richardabendroth** [comment]
I've recreated a 74xxx circuit and depending on the complexity of the circuit it's easier to compare the gates if they are actually identical. That's why I asked for the input negation back then as well.

**Comment by flandreas** [comment]
Ah, I see. I guess that's a good reason to implement this feature.
