### ISSUE TITLE
Input/Output names when copying&pasting

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#590]
When copying and pasting Inputs/Outputs, the newly assigned name is either I[n] or O[n]. While this makes sense when dragging a new Input/Output from the Library, it would be great when using copy&paste instead, when the name would be copied as well but maybe with a (2) or something appended. E.g. when copying an Input with name "Σ1" it would be great if the new name would be "Σ1 (2)" or even "Σ2" if somehow possible.

**Comment by flandreas** [comment]
Thank you Richard, this is an interesting suggestion, I think we will implement this.

**Comment by richardabendroth** [comment]
Another thought: You could instead expose the naming pattern as properties on the circuit for input, output, and input/output. Something like: 
Input Naming: I{n}
Output Naming: O{n}
Input/Output: IO{n}

74xx series IC's often have inputs like A, B, C, D and outputs with numbers, which would look like: 
Input Naming: {L}
Output Naming: {n,0} (0 being the starting number)

And one could also do things like "Σ{n,1}". 

And you should definitely add the "Input/Output" components to the Inputs and Outputs categories.

**Comment by flandreas** [comment]
Requirement "And you should definitely add the "Input/Output" components to the Inputs and Outputs categories" extracted to separate issue #604.

**Comment by flandreas** [comment]
Requirement "Expose naming pattern" extracted to separate issue #612.

**Comment by flandreas** [comment]
Implemented first requirement:
- If name adheres to pattern "text,number", the pasted name will be "text,number+1", or the next available free number respectively
- Else, apply the pattern "Text (2)"
