### ISSUE TITLE
Indicate that "Bulk property editing" is limited to 8 components

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#591]
When selecting more than 8 identical components, the "Properties" area becomes blank: 

![image](https://github.com/flandreas/antares/assets/25486087/9fb1c34f-481c-4ff4-ad83-133d7301347c)
![image](https://github.com/flandreas/antares/assets/25486087/b78e83df-9784-460a-bf08-58bbcc7323e9)

**Comment by flandreas** [comment]
@richardabendroth Yes, the number of components for which "Edit properties of multiple components" is possible is intentionally limited to 8. This feature is very computation intense, as it has to find the common denominator of the properties of all selected components. "Select All" in a circuit with hundreds of components would perhaps make your computer explode. I thought the number 8 was a nice IT number. Would you wish a larger number?

**Comment by richardabendroth** [comment]
Oh I see. Maybe you should have a message in the properties area indicating this, like: "Bulk editing of properties is limited to 8 components for performance reasons" or "too many components selected".

**Comment by flandreas** [comment]
You're right, I'll do that.
