### ISSUE TITLE
Connect wire with another wire

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#593]
When splitting two subnets and then trying to reconnect them, the first attempt fails. 
![image](https://github.com/flandreas/antares/assets/25486087/23ff2bc8-d9f0-4749-8a47-66c7fabfdef0)
![image](https://github.com/flandreas/antares/assets/25486087/a1557b60-bb2e-4770-991d-f6628a43df1a)

But after fiddling a while, one can get it to work, by first branching off a new wire that is connected to noting, then clicking it again and moving the bubble over the wire of the target net: 
![image](https://github.com/flandreas/antares/assets/25486087/5f7184ca-b25f-4ba3-bb77-a4f98ea8cb70)
![image](https://github.com/flandreas/antares/assets/25486087/7b28699c-b0ad-481c-80c0-bf8c6940d085)

Is this the desired behavior?

**Comment by flandreas** [comment]
That's a missing feature. The tool for creating junctions does not yet support wires as target, while the tool for dragging wire endpoints does.
