### ISSUE TITLE
Library explorer allows dragging Circuit into itself

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#597]
In the library explorer, one can drag a Circuit into itself. When releasing the mouse button, a popup appears if the user wishes to move the circuit. This should not be possible.

**Comment by flandreas** [comment]
Actually, you cannot drop a circuit onto itself. This is already prevented.

However, you can drag a circuit and drop it within the same directory just right before or right after it current position, effectively leading to a no-op. This is now prevented as well.
