### ISSUE TITLE
Mnemonic of buffer

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#600]
Currently, the mnemoic for the buffer is a straight wire. But a buffer is actually a transistor of the opposite type of a NOT gate. Wouldn't it be nice for teaching, if the buffer would reflect its actual purpose (regenerating the input signal)? Together with #113  this would be a great tool for learners to understand what input and output inversion actually means electronically.

**Comment by flandreas** [comment]
Your are right. Thank you for this suggestion. I will replace the "straight line" mnemonic of the buffer with the inversion of the NOT mnemonic.
