### ISSUE TITLE
Allow input naming on gates and maybe any other component type

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#603]
Like the option "Output Name" on gates, it would be great if inputs also could be named: 
![image](https://github.com/flandreas/antares/assets/25486087/358490a4-1b05-4f88-a4c9-2413b39b70e1)

Maybe this could also be available for all inputs/outputs of components.

**Comment by flandreas** [comment]
Maybe "any other component type" besides sub circuits, whose input pins already have a name.

**Comment by flandreas** [comment]
Implemented for logic gates
