### ISSUE TITLE
Missing space in tooltip

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#605]
The Circuit input tooltip misses a space within the descriptive text: 
![image](https://github.com/flandreas/antares/assets/25486087/a2df9e88-29c2-4ade-9caf-b28bc9588fb8)

**Comment by flandreas** [comment]
@richardabendroth Thank you for reporting this.

Seems to be a Windows-specific rendering problem. On macOS, rendering is better.

<img width="409" alt="Screenshot 2023-07-20 at 10 46 40" src="https://github.com/flandreas/antares/assets/24633141/d3f0fc25-c79c-4703-b0ee-e3480535c23b">

**Comment by flandreas** [comment]
Rendering has been completely reworked to support styled text according to #592.
