### ISSUE TITLE
Module to interconnect with other applications

### ISSUE THREAD

**Issue by wmurbina** [flandreas/antares#614]
My question is, I could create a module that allows to interconnect with other applications for example with labview.
It could be by serial interface or TCP sockect.
In this video you can see how the Proteus simulation interacts with labview. [https://www.youtube.com/watch?v=KbpBKn2fYdU](url)

Thank you.

**Comment by flandreas** [comment]
@wmurbina Thank you for the suggestion. Similar to #122.
In particular, I would consider interconnection with specific applications like labview only if a sufficient number of user would support that request.
