### ISSUE TITLE
Export the design to C language and compile for arduino

### ISSUE THREAD

**Issue by wmurbina** [flandreas/antares#650]
Greetings.
You could add a feature that allows to export the design to C language and compile for arduino. I am currently doing this functionality with Matlab but I would like to be able to do it with Antares since it has more elements for digital systems.

**Comment by flandreas** [comment]
@wmurbina This would require not only to create C code representing a circuit, but probably also to rewrite the entire simulation engine as well as the base libraries to C. Sorry, this is too much to ask for.
