### ISSUE TITLE
Explorer tree items right-cropped on Windows

### ISSUE THREAD

**Issue by flandreas** [flandreas/antares#663]
When running Antares on Windows with display settings set to 200%, the items in the explorer are slightly cropped on the right side, i.e. their bounding box is not large enough to display the entire text.

![cropped-explorer-nodes](https://github.com/flandreas/antares/assets/24633141/382e78c3-6a9f-4876-84bc-06d32d113a22)

**Comment by fpw** [comment]
Same issue on my screen with 125% - which is Windows' default for this screen.

```java -version
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)
``` 

![grafik](https://github.com/flandreas/antares/assets/5798899/f792d848-dbd3-4124-a4df-697fa89074d8)
