### ISSUE TITLE
Error while loading rating data

### ISSUE THREAD

**Issue by Hougaarden** [flandreas/antares#688]
I got this message when I tried to leave a rating (Windows 11)

![Rating](https://github.com/flandreas/antares/assets/7812354/f02cd66d-99e0-41e5-9c33-a4ebe8f667e1)
.

**Comment by flandreas** [comment]
@Hougaarden Thank you for reporting this. Yes we know, the backend cloud service we use for rating and usage counting are down since two days. We are currently looking into the issue; maybe we've exceeded some free usage quotas of the cloud service.

But thanks for trying to rate Antares :-)

**Comment by flandreas** [comment]
@Hougaarden Backend services are back online, rating does work again.

**Comment by Hougaarden** [comment]
Andreas,

Thank you for the quick response. The rating has already been given.
Too bad you can only enter 20 characters of text.
I would have liked to note that it is a pity that users cannot share their projects through the program, as in EveryCircuit, for example..

Regards, Wilfried
Van: Andreas Fleischmann ***@***.***>
Verzonden: woensdag 7 februari 2024 20:19
Aan: flandreas/antares ***@***.***>
CC: Hougaarden ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [flandreas/antares] Error while loading rating data (Issue #688)


@Hougaarden<https://github.com/Hougaarden> Backend services are back online, rating does work again.
