### ISSUE TITLE
Oscilloscope not working as expected

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#690]
I have a circuit with a clock and a subcircuit that create a quadrature output that progresses on every clock cycle: 
A:hi B:lo -> A:hi B:hi -> A:lo B:hi -> A:lo B:lo -> ... 

However, the output of the oscilloscope looks like this: 
![image](https://github.com/flandreas/antares/assets/25486087/136d0341-bd49-4895-b156-f3e29c6f566c)

Am I using it wrong? Even the clock pulses are somehow transitioning in an unexpected way.

**Comment by flandreas** [comment]
@richardabendroth You are using the oscilloscope in "Clocked mode", but the clock signal (the first row in the oscilloscope) seems to be an output of your circuit.
Try setting up the oscilloscope with the blue CLK signal as first row in the oscilloscope.
