### ISSUE TITLE
Can't edit custom symbol pins anymore in 1.11.0

### ISSUE THREAD

**Issue by fpw** [flandreas/antares#712]
After updating Antares to 0.11.0, I can't edit the pin properties in my custom symbols: The properties window is empty and stdout shows this:

`2024-04-15 20:23:28,306  WARN [AWT-EventQueue-0] (AbstractPropertyPanelSwing.kt:197) - Could not instantiate Properties for ch.scorpion.antares.view.container.DigitalPortViewComponent: Exception java.lang.NoSuchMethodException: Unknown property 'largeExternalPortLabelDist' on class 'class ch.scorpion.antares.view.container.DigitalPortViewComponent'`

Screenshot shows how the properties view is empty:

![grafik](https://github.com/flandreas/antares/assets/5798899/db2374a6-0bd6-48e7-812a-fb840ae6ffe0)

**Comment by flandreas** [comment]
Reproducible, thanks for reporting!

**Comment by flandreas** [comment]
Fixed. This is a blocker, justifies a bugfix release soon.
