### ISSUE TITLE
When deleting all wires leading to a junction, the junction can't be deleted anymore.

### ISSUE THREAD

**Issue by demondave** [flandreas/antares#72]
![image](https://user-images.githubusercontent.com/35665396/113290553-1c54ea00-92f2-11eb-881c-b01fa4383b7d.png)

**Comment by flandreas** [comment]
Thank you for reporting this, but I'm not able to reproduce it. When I try it with a circuit like the one in the lower part of your screenshot (a switch connected with 2 LED), and I select any combination of wire segments, and press then DEL, the junction is always deleted as well. Can you please explain how you deleted the wires that lead to this situation?

**Comment by flandreas** [comment]
Ah, now I see. Thank you!
