### ISSUE TITLE
Joining wires can lead to corrupt pin connections

### ISSUE THREAD

**Issue by flandreas** [flandreas/antares#726]
This can be caused by joining open-ended wires or deleting wire junctions. Leads to pins not properly connected to the net of the wire, which results in simulation not working as expected.

Detected in #713.

**Comment by flandreas** [comment]
Thanks! Reopened

**Comment by flandreas** [comment]
Cannot be reproduced generally with a simple circuit having the same structure like the problematic region like in the video. 

However, it AN be reproduced using the dump provided in #713 with exactly the wire segment you've deleted. I'll investigate..

**Comment by flandreas** [comment]
Reproducible when deleting the selected wire in this simplified circuit:

<img width="273" alt="Screenshot 2024-04-25 at 16 44 22" src="https://github.com/flandreas/antares/assets/24633141/d0993170-b227-4e02-ac89-f486a62075cf">

The problem occurs when the wire that gets joined is connected with yet another junction node.

**Comment by fpw** [comment]
Great find, I think all instances in which I've encountered this bug previously were related to long wire junction ladders like this.

**Comment by flandreas** [comment]
Unfortunately I think I've introduced this one with my last fix. The scenario above isn't reproducible in the productive version 1.11.
