### ISSUE TITLE
Focusable components should overwrite global hotkey actions

### ISSUE THREAD

**Issue by flandreas** [flandreas/antares#727]
Extracted from #725 

Components like keyboard are currently not able to consume keys like space, because they are intercepted and consumed by top-level keyboard bindings. For example, the space key is used to pause and resume the simulation, preventing the user from entering spaces in the keyboard component during simulation.

**Comment by fpw** [comment]
Great to see this fixed, thanks! 

There seems to be a small problem with it where sometimes hotkeys don't work anymore after stopping the simulation. Example:

- create a circuit with a keyboard
- start the simulation by clicking play
- focus the keyboard
- stop the simulation by clicking play

-> Now hotkeys like pressing delete to delete a component no longer work.

**Comment by flandreas** [comment]
OK, thanks! I've forgot to clear the focus after the simulation has ended. Although I don't know yet how to solve this, because there can many independent simulations be running at the same time (using "Open in new window.."), but there is only one global focus manager. I have to think about that..

**Comment by flandreas** [comment]
@fpw Fixed by resetting the FocusManager after simulation has stopped. This leaves the issue that a second open simulation window looses its focused component, but I think we can live with this corner case for now.
