### ISSUE TITLE
Error 404 when trying to download examples

### ISSUE THREAD

**Issue by logoliv** [flandreas/antares#762]
When I click on the download buttons in the https://www.antarescircuit.io/docs/examples/examples/ pages I obtain a 404 error.

**Notes :**
It's mandatory to add an option to disable tooltips : they're distracting and we don't need to know everytime the truth table of an AND gate or the name of the components in our circuits...
It would also be nice to replace "alt + left click" to pan by "space + left click", because alt is already used by menus and to trace wires : it tries to pan everytime I want to add a wire (and middle click is not practical).

**Comment by flandreas** [comment]
Thank you for your feedback!

Download links: Fixed.

Disable tooltips: Okay, that makes sense, I'll create a separate issue for this. There is already the "Show tips for beginners" user preference, but I didn't think of truth tables and component name tooltips also to be disabled.

Pan: I understand your request such that you'd like another "Pan method" option in the View user preferences for "space + left click".  I'll create  a separate issue for this. Just out of curiosity: Why do you think middle click is not practical? That's the option I'm personally using, also in other applications that support panning.

**Comment by logoliv** [comment]
Thanks for your answer and for fixing download links :)

I think it's a question of personal preferences concerning the middle mouse button : I have no problem using the mouse wheel but I don't feel comfortable using it as a button. Some applications that don't have contextual menus (but Antares has) give the option to use the right button for pan and it feels OK through... But I certainly must not be the only one with the same feeeling.

I've also noticed that pressing the alt key highlights the file menu : you don't have menus shortcuts (and it's good like that) so you don't need that, maybe disable it if you find the instruction to do that, but it's just a detail.

And at last: thanks for developping Antares ! I was searching a replacement solution for the old Logisim, and your app has a good design, a nice feeling and already some nice functionalities :)
