### ISSUE TITLE
Text color lighter than expected when using Darcula theme

### ISSUE THREAD

**Issue by logoliv** [flandreas/antares#765]
Here's an example when I choose "green" as color, but it's the same for all colors when using this theme :

![image](https://github.com/flandreas/antares/assets/56048110/a241b5bb-e910-4654-a372-f4fd25fe97b5)

**Comment by flandreas** [comment]
@logoliv Thank you for pointing that out, I wasn't aware of this.

The reason why it currently behaves like that is that the text color has been hand-crafted for applications like rectangles with text, where there is a coloured background of the same color type. Obviously, this doesn't work very well with plain texts without background.

<img width="671" alt="Screenshot 2024-06-22 at 15 13 36" src="https://github.com/flandreas/antares/assets/24633141/fe110378-d555-44de-92d1-43b8e7d68433">

I'll think about what a good strategy for choosing the text color in this use case could be. Maybe the background color..

**Comment by flandreas** [comment]
I'll go with the foreground (i.e. border) color:

<img width="671" alt="Screenshot 2024-06-22 at 15 28 12" src="https://github.com/flandreas/antares/assets/24633141/e3aae7ff-cd40-44db-a52a-f0320d25c946">

**Comment by logoliv** [comment]
nice 👍
