### ISSUE TITLE
Wire is accidentally disconnected when moving small components like Net/Constant 

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#77]
When moving for example Net/Constant within a circuit sometimes the user grabs the wire handle without noticing. This disconnects the wire without the user knowing. The user is not able to see the problem.

**Comment by flandreas** [comment]
In order to avoid accidental reconnects (especially on small components), the user has now to press ALT when hovering with the mouse over a connected port. A port offering reconnect now shows a highlighter that differs from the one used for creating junctions off existing wires.
