### ISSUE TITLE
Simulation doesn't launch when initializing subcircuit inputs with DSL script

### ISSUE THREAD

**Issue by logoliv** [flandreas/antares#778]
If I add "PRE = 1" and "CLR = 1" to the init part of the function parameter the simulation doesn't launch anymore.
Everything is fine with only "Q = 0" in init.

Component joined (try it as a subcircuit because it has a bit width parameter).
[DFFE.zip](https://github.com/user-attachments/files/16046042/DFFE.zip)

**Note** : in fact there's no need to do that, because the component is only scripted and it works fine without a defined value for PRE and CLR. So I just opened this issue as reference, to know if your scripting language blocks the initialisation of component input or if it's really a bug.

**Comment by flandreas** [comment]
Thank you for reporting this.

Well first of all, PRE and CLR are input pins. You shouldn't try to set a value to them. You can only set a value to variables or to output pins.

However, there are two issues in Antares:
- Although syntactically correct, the semantic analyser of the scripting engine should report this as a script error.
- Antares shouldn' produce an unexpected error in this situation
