### ISSUE TITLE
Sign Installers to prevent InstallShield/GateKeeper warnings

### ISSUE THREAD

**Issue by Kitick** [flandreas/antares#86]
So when you download the exe to install Antares, windows smart screen thing stops it from running, and you have to tell it that's its alright and run anyway. This has been happening in other releases, I just was reminded about it from 5.1.

Just wanted to let you know that happens, and I believe the way to fix it is to just add a digital signature to the exe.

**Comment by flandreas** [comment]
Yeah, same problem on Mac, were I also don't have a developer license yet. It's probably time now to make the investment and get one... :-)

**Comment by Kitick** [comment]
Lol, I would yeah, considering how far Antares is coming along! And other projects would benefit as well.
