### ISSUE TITLE
Graphical glitch with text when starting simulation

### ISSUE THREAD

**Issue by Kitick** [flandreas/antares#87]
When you have text on the board like I have in a project, if you start the simulation when the text is not in view under the screen, it shows the text. And it stays their even after stopping. all until you restart the simulation with all text visible

Just wanted to point it out.

![image](https://user-images.githubusercontent.com/34259991/118406327-70acf280-b630-11eb-84bf-75e80bd84831.png)
![image](https://user-images.githubusercontent.com/34259991/118406334-80c4d200-b630-11eb-89b2-bd6bd10dfa82.png)

**Comment by flandreas** [comment]
Thank you! Yes, that's an old item on my "hidden" TODO list, glad you made it official now :-) Will soon look into it.

**Comment by Kitick** [comment]
glad I could help!
