### ISSUE TITLE
Some combination of deleting wires can cause a junction to still exist

### ISSUE THREAD

**Issue by Kitick** [flandreas/antares#93]
I was deleting some wires to reconnect them differently, and somehow I got it to leave the junction, and I cant get rid of it. I can move it, and it even lights up as if it was powered; but its just annoying and I cant delete it. Simply says some elements cannot be deleted. I also managed to do it twice.

There in the top right corner of the terminal

![image](https://user-images.githubusercontent.com/34259991/118768717-2eec9980-b834-11eb-8061-8112533ae818.png)

**Comment by flandreas** [comment]
I you don't mind, you can send me your project ZIP and I can quickly remove the dangling junctions and send you back the corrected project.

I assume you don't remember the sequence of selections and deletions that lead to this situation? It would help to reproduce and fix the bug.

**Comment by Kitick** [comment]
No problem, and so what I can guess, it happens when I'm doing stuff with multiple wires, that have a junction. But I'm not quite sure exactly what did it.

Also just a side note, have you read my response to the propagation timings suggestion? I know your probably really busy so its fine if you haven't.

But here's the current project: [Computer.zip](https://github.com/flandreas/antares/files/6506651/Computer.zip)

**Comment by flandreas** [comment]
Here is your fixed project: [Computer.zip](https://github.com/flandreas/antares/files/6506799/Computer.zip). BTW: Your circuits are growing impressively :-)

No sorry, your propagation timing suggestion is still on my todo list. I'm currently on a deep-dive in fixing critical bugs in Antares, but I will answer as soon as I can...

**Comment by richardabendroth** [comment]
Have been able to reproduce. Can also be reproduced by copy/pasting some components that have wires with junctions attached to them. When selecting the components via mouse with a select rect that are already connected to wires with junctions, make sure to only select the components and the junctions but **not** the wires.  Then copy and paste and you are left with some floating junctions that can be moved but not deleted. 
![image](https://user-images.githubusercontent.com/25486087/119373300-8bc6d480-bcb8-11eb-9a5c-c07a72b492dc.png)

**Comment by flandreas** [comment]
The issue with copy/paste has been fixed. By only deleting wires, I was not able to reproduce the problem, at least with the current 0.6.0-dev version. Let's leave it this way and see if the problem still occurs in the next version.

**Comment by flandreas** [comment]
Implemented support for deleting unconnected junctions as to help users to clean up their circuits if the problem should still occur. But please, keep on reporting if the problem persists.
