### ISSUE TITLE
Moving Small Circles in Symbol View does not work

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#94]
In Symbol View, small circles (i.e. for inverted inputs/outputs) cannot be moved since the circle shape does not show the move cursor. It only shows the other cursors. Additionally, those cursors are offset quite a lot towards the right and bottom of the shape. 

Platform: Windows 10

**Comment by flandreas** [comment]
Okay, now I see your point (besides the fact that I recommend to use property "Logic" for inverted ports).

The size of the 8 handles to be used for resizing objects does not change with the zoom factor. This is by intention. However, the sensitivity area of the handles used to decide which mouse cursor to show does not correctly reflect the size of the handles. So this is a bug.

**Comment by richardabendroth** [comment]
I think I am not having that option:
![image](https://user-images.githubusercontent.com/25486087/118868678-c0b3df80-b8e4-11eb-812d-9d0d26283549.png)

**Comment by flandreas** [comment]
Oh no, what a pity! This is a bug, silently swallowed by Antares. Sorry for that. This gives reason for a release 0.5.2 soon.

**Comment by richardabendroth** [comment]
Nice! Having worked with Antares and seeing the cleverness you put into it, I should have suspected there was a more elaborated way than mine of creating circles by hand. 🙈

**Comment by flandreas** [comment]
Bug "Property not shown" fixed by #95 in release 0.5.2. The "Handles" problem will be targeted in 0.6.0.

**Comment by flandreas** [comment]
Fixed the sensitivity area of handles.
