### ISSUE TITLE
Sum Symbol in Full Adder Symbol shows broken in Explorer and Circuit

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#97]
![image](https://user-images.githubusercontent.com/25486087/118845835-69097a00-b8cc-11eb-9d28-659ec5b77ac5.png)

Platform: Windows 10
Version: 0.5.1

**Comment by flandreas** [comment]
Should really be a ∑. Seems to be a problem of proper unicode usage of Antares on Windows.

**Comment by richardabendroth** [comment]
Funny thing is, it works in the Symbol editor:
![image](https://user-images.githubusercontent.com/25486087/118869151-52235180-b8e5-11eb-9a23-d1928d36328a.png)
