### ISSUE TITLE
User Folders cannot be renamed

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#98]
After creating a folder within the Project tree, the folder cannot be renamed. The Name property in the Properties window is disabled. 
![image](https://user-images.githubusercontent.com/25486087/118872573-fa86e500-b8e8-11eb-994a-bb8864607a47.png)

**Comment by flandreas** [comment]
The bug was in how this panel uses the authorization subsyste, which is used to make sure that the user can change his own data, but not the built-in libraries.
